name: Docker Image CI

on:
    push:
        branches: ["master"]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    run-on-aws-ec2:
        runs-on: self-hosted
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v3

            - name: Create .env file
              run: |
                  rm -rf .env || true
                  touch .env
                  echo '${{ secrets.ENV_KEYS }}' >> .env
                  cat .env
            - name: Login to GitHub Container Registry on AWS EC2
              run: |
                  sudo docker login ghcr.io -u naimur2 -p ${{secrets.GH_KEY}}

            - name: remove existing docker container
              run: |
                  sudo docker stop zinfinity-app || true
                  sudo docker rm zinfinity-app || true

            - name: remove existing docker image
              run: |
                  sudo docker rmi zenfinity || true

            - name: remove existing docker volume
              run: |
                  sudo docker volume rm zinfinity-app-client || true

            - name: build docker image
              run: |
                  sudo docker build -t zenfinity .

            - name: Run docker container
              run: |
                  sudo docker run -d --name zinfinity-app --env-file .env -p 3000:3000 -v zinfinity-app-client:/app zenfinity